apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miyo-cloud-sandbox
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: miyo-infra-sandbox
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: miyo-sandbox
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: projects/sandbox
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true